# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d43ecdb15315437401372e4e51ed21f9ce16ce55d0cdf40b832d57b0d1fdfb9f137dd859ee689c1a0c221c90f53593cfef7198376cbd83992765966c9df5c184

test:
  secret_key_base: faf6a9ab482e50568712be8a0edbe02cff1eabcc3d958d68018ccd2f5f5786de28798b1b92b3d0885c71dae76dddc5a88752fd949f04573f48b84b9ee86d495f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
